/* Generated By:JJTree: Do not edit this line. ASTMINUS_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMINUS_op extends SimpleNode {
  public ASTMINUS_op(int id) {
    super(id);
  }

  public ASTMINUS_op(Syntax p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fa19afc34c9aa4ec99852ddd2fb57b92 (do not edit this line) */
