/* Generated By:JJTree: Do not edit this line. ASTOR_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOR_op extends SimpleNode {
  public ASTOR_op(int id) {
    super(id);
  }

  public ASTOR_op(Syntax p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=005f9566f5ffa12505e4df091fa32680 (do not edit this line) */
