/* Generated By:JJTree: Do not edit this line. ASTPLUS_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPLUS_op extends SimpleNode {
  public ASTPLUS_op(int id) {
    super(id);
  }

  public ASTPLUS_op(Syntax p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=91731da4af99102cb24f518f693ecad3 (do not edit this line) */
