/* Generated By:JJTree: Do not edit this line. ASTVoid.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVoid extends SimpleNode {
  public ASTVoid(int id) {
    super(id);
  }

  public ASTVoid(Syntax p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=86bb6a1057703f0069785bc96fd8b855 (do not edit this line) */
