/* Generated By:JavaCC: Do not edit this line. SyntaxConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CALL = 1;
  /** RegularExpression Id. */
  int VAN = 2;
  /** RegularExpression Id. */
  int HOST = 3;
  /** RegularExpression Id. */
  int PLEDGE = 4;
  /** RegularExpression Id. */
  int REAR = 5;
  /** RegularExpression Id. */
  int SCOUT = 6;
  /** RegularExpression Id. */
  int AT = 7;
  /** RegularExpression Id. */
  int AS = 8;
  /** RegularExpression Id. */
  int CLAIM = 9;
  /** RegularExpression Id. */
  int WHERE = 10;
  /** RegularExpression Id. */
  int ALL = 11;
  /** RegularExpression Id. */
  int LBRACE = 12;
  /** RegularExpression Id. */
  int RBRACE = 13;
  /** RegularExpression Id. */
  int LPAR = 14;
  /** RegularExpression Id. */
  int RPAR = 15;
  /** RegularExpression Id. */
  int LSQUARE = 16;
  /** RegularExpression Id. */
  int RSQUARE = 17;
  /** RegularExpression Id. */
  int DOUBLECOLON = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int SEMICOLON = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int STRING = 22;
  /** RegularExpression Id. */
  int NUM = 23;
  /** RegularExpression Id. */
  int ASSIGNATION = 24;
  /** RegularExpression Id. */
  int PLUS = 25;
  /** RegularExpression Id. */
  int MINUS = 26;
  /** RegularExpression Id. */
  int MULT = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int LESSTHAN = 29;
  /** RegularExpression Id. */
  int MORETHAN = 30;
  /** RegularExpression Id. */
  int EQUALS = 31;
  /** RegularExpression Id. */
  int NOTEQUALS = 32;
  /** RegularExpression Id. */
  int WRITE = 33;
  /** RegularExpression Id. */
  int READ = 34;
  /** RegularExpression Id. */
  int CHARGE = 35;
  /** RegularExpression Id. */
  int WHILE = 36;
  /** RegularExpression Id. */
  int DO = 37;
  /** RegularExpression Id. */
  int FOR = 38;
  /** RegularExpression Id. */
  int SEPARATOR = 39;
  /** RegularExpression Id. */
  int IF = 40;
  /** RegularExpression Id. */
  int ELSE = 41;
  /** RegularExpression Id. */
  int OR = 42;
  /** RegularExpression Id. */
  int AND = 43;
  /** RegularExpression Id. */
  int NUMBER = 44;
  /** RegularExpression Id. */
  int ID = 45;
  /** RegularExpression Id. */
  int DOUBLEQUOTED = 46;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"call banners\"",
    "\"van\"",
    "\"host\"",
    "\"pledge\"",
    "\"rear\"",
    "\"Scout\"",
    "\"At\"",
    "\"As\"",
    "\"Claim\"",
    "\"Where\"",
    "\"all\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\",\"",
    "\";\"",
    "\"int\"",
    "\"String\"",
    "\"num\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"Write\"",
    "\"Read\"",
    "\"Charge\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"|\"",
    "\"if\"",
    "\"else\"",
    "\"||\"",
    "\"&&\"",
    "<NUMBER>",
    "<ID>",
    "<DOUBLEQUOTED>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
