/* Generated By:JavaCC: Do not edit this line. SyntaxVisitor.java Version 5.0 */
public interface SyntaxVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTDeclaration node, Object data);
  public Object visit(ASTDecl node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTPLUS_op node, Object data);
  public Object visit(ASTMINUS_op node, Object data);
  public Object visit(ASTOR_op node, Object data);
  public Object visit(ASTNOT_op node, Object data);
  public Object visit(ASTMULT_op node, Object data);
  public Object visit(ASTDIV_op node, Object data);
  public Object visit(ASTAND_op node, Object data);
  public Object visit(ASTExp node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTID node, Object data);
  public Object visit(ASTString node, Object data);
}
/* JavaCC - OriginalChecksum=3b48ba9e1cf8282e37cce602b648c4e8 (do not edit this line) */
