/* Generated By:JavaCC: Do not edit this line. SyntaxTreeConstants.java Version 5.0 */
public interface SyntaxTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDECLARATION = 2;
  public int JJTDECL = 3;
  public int JJTSTATEMENT = 4;
  public int JJTPLUS_OP = 5;
  public int JJTMINUS_OP = 6;
  public int JJTOR_OP = 7;
  public int JJTNOT_OP = 8;
  public int JJTMULT_OP = 9;
  public int JJTDIV_OP = 10;
  public int JJTAND_OP = 11;
  public int JJTEXP = 12;
  public int JJTNUMBER = 13;
  public int JJTID = 14;
  public int JJTSTRING = 15;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Declaration",
    "Decl",
    "Statement",
    "PLUS_op",
    "MINUS_op",
    "OR_op",
    "NOT_op",
    "MULT_op",
    "DIV_op",
    "AND_op",
    "Exp",
    "Number",
    "ID",
    "String",
  };
}
/* JavaCC - OriginalChecksum=1dcae7173d73b609f6f497dd9022204f (do not edit this line) */
